In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

Matplotlib is building the font cache; this may take a moment.

In [3]:
df = pd.read_csv("../data/traffic_events.csv")

df.head()

,id,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,start_datetime,end_datetime,status,authenticated,modified_datetime,map_file,direction,description,veh_type,veh_no,corridor,priority,cargo_material,reason_breakdown,age_of_truck,created_date,route_path,client_id,created_by_id,last_modified_by_id,assigned_to_police_id,citizen_accident_id,comment,police_station,meta_data,kgid,resolved_at_address,resolved_at_latitude,resolved_at_longitude,closed_by_id,closed_datetime,resolved_by_id,resolved_datetime,gba_identifier,zone,junction
0,FKID000000,unplanned,13.040004,77.518099,0.000000,0.000000,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",NaN,vehicle_breakdown,False,2024-03-07 17:01:48.111+00,NaN,closed,yes,2024-03-07 19:35:47.871698+00,NaN,NaN,s m circle in coming man track,lcv,FKN00GL0000,Tumkur Road,High,NaN,NaN,NaN,2024-03-07 17:03:51.164032+00,NaN,1,FKUSR00000,FKUSR00001,NaN,NaN,NaN,Peenya,NaN,FKKG000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FKID000001,unplanned,12.921876,77.645158,0.000000,0.000000,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",NaN,vehicle_breakdown,False,2024-01-30 04:07:24.173+00,NaN,resolved,yes,2024-01-30 04:17:46.828979+00,NaN,NaN,Starting problem,heavy_vehicle,FKN00GL0001,ORR East 1,High,NaN,NaN,NaN,2024-01-30 04:08:22.954979+00,NaN,1,FKUSR00002,FKUSR00001,NaN,NaN,NaN,HSR Layout,NaN,FKKG000001,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",12.921876,77.645158,NaN,NaN,FKUSR00002,2024-01-30 04:17:46.828355+00,NaN,NaN,NaN
2,FKID000002,unplanned,12.955622,77.585708,0.000000,0.000000,"Lalbagh Main Road, Dr Sri Shantaveera Swami Ci...",NaN,others,False,2023-11-11 06:18:03.343+00,NaN,closed,yes,2024-01-30 04:56:03.282003+00,NaN,NaN,ಊರ್ವಶಿ ಜಂಕ್ಷನ್ ನಲ್ಲಿ ಒಳಚರಂಡಿ ಚೇಂಬರ್ ಗೆ ಹೊಸದಾಗಿ...,NaN,NaN,Non-corridor,Low,NaN,NaN,NaN,2023-11-11 06:20:00.989398+00,NaN,1,FKUSR00003,FKUSR00001,NaN,NaN,NaN,Wilson Garden,NaN,FKKG000002,NaN,NaN,NaN,FKUSR00003,2024-01-30 04:56:03.281509+00,NaN,NaN,Bengaluru Central Corporation,Central Zone 2,UrvashiJunction
3,FKID000003,unplanned,13.006147,77.579435,13.006239,77.579516,"Sankey Road, Bashyam Circle, Sadashiva Nagar, ...","Sankey Road, Palace Orchard Upper, Sadashiva N...",tree_fall,True,2024-03-07 17:56:55.061+00,NaN,closed,yes,2024-03-14 07:42:05.55005+00,NaN,NaN,tree fall,NaN,NaN,Non-corridor,Low,NaN,NaN,NaN,2024-03-07 17:58:56.696892+00,NaN,1,FKUSR00004,FKUSR00001,NaN,NaN,NaN,Sadashivanagar,NaN,FKKG000003,NaN,NaN,NaN,FKUSR00004,2024-03-14 07:42:05.54944+00,NaN,NaN,NaN,NaN,NaN
4,FKID000004,unplanned,12.953980,77.585233,0.000000,0.000000,"Lalbagh Fort Road, Lalbagh Main Gate Junction,...",NaN,vehicle_breakdown,False,2024-01-30 04:56:32.348+00,NaN,closed,yes,2024-01-30 05:35:17.33908+00,NaN,NaN,[LOCATION] ಪೈಪ್ [PERSON] ವಾಹನ ಆಫ್ ಆಗಿರುತ್ತದೆ ಸರ್,private_bus,FKN00GL0002,Non-corridor,Low,NaN,NaN,NaN,2024-01-30 04:58:55.937662+00,NaN,1,FKUSR00003,FKUSR00001,NaN,NaN,NaN,Wilson Garden,NaN,FKKG000002,NaN,NaN,NaN,FKUSR00003,2024-01-30 05:35:17.338283+00,NaN,NaN,NaN,NaN,LalbaghMainGateJunc

In [4]:
df.shape

(8173, 46)

In [5]:
df.columns.tolist()

['id',
 'event_type',
 'latitude',
 'longitude',
 'endlatitude',
 'endlongitude',
 'address',
 'end_address',
 'event_cause',
 'requires_road_closure',
 'start_datetime',
 'end_datetime',
 'status',
 'authenticated',
 'modified_datetime',
 'map_file',
 'direction',
 'description',
 'veh_type',
 'veh_no',
 'corridor',
 'priority',
 'cargo_material',
 'reason_breakdown',
 'age_of_truck',
 'created_date',
 'route_path',
 'client_id',
 'created_by_id',
 'last_modified_by_id',
 'assigned_to_police_id',
 'citizen_accident_id',
 'comment',
 'police_station',
 'meta_data',
 'kgid',
 'resolved_at_address',
 'resolved_at_latitude',
 'resolved_at_longitude',
 'closed_by_id',
 'closed_datetime',
 'resolved_by_id',
 'resolved_datetime',
 'gba_identifier',
 'zone',
 'junction']

In [6]:
missing = (
    df.isnull()
    .sum()
    .sort_values(
        ascending=False
    )
)

missing

meta_data                8173
comment                  8173
map_file                 8173
direction                8130
resolved_at_longitude    8099
resolved_at_latitude     8099
resolved_at_address      8099
resolved_by_id           8099
resolved_datetime        8099
citizen_accident_id      8045
assigned_to_police_id    8045
route_path               8036
cargo_material           7897
age_of_truck             7897
reason_breakdown         7897
end_datetime             7683
end_address              7486
junction                 5663
closed_by_id             5032
closed_datetime          5032
zone                     4729
gba_identifier           4729
veh_no                   3287
veh_type                 3286
description              1360
kgid                      259
endlongitude              169
endlatitude               169
corridor                   20
address                     3
last_modified_by_id         3
created_by_id               2
priority                    2
latitude                    0
longitude                   0
requires_road_closure       0
event_cause                 0
police_station              0
start_datetime              0
status                      0
client_id                   0
authenticated               0
created_date                0
modified_datetime           0
event_type                  0
id                          0
dtype: int64

In [7]:
df["event_type"].value_counts()

event_type
unplanned    7706
planned       467
Name: count, dtype: int64

In [8]:
df["event_cause"].value_counts().head(30)

event_cause
vehicle_breakdown       4896
others                   638
pot_holes                537
construction             480
water_logging            458
accident                 365
tree_fall                284
road_conditions          170
congestion               136
public_event              84
procession                72
vip_movement              20
protest                   15
Debris                    12
test_demo                  3
Fog / Low Visibility       2
debris                     1
Name: count, dtype: int64

In [9]:
df[
[
"event_type",
"event_cause",
"description",
"reason_breakdown"
]
].sample(20)

,event_type,event_cause,description,reason_breakdown
5981,unplanned,pot_holes,[PERSON] bridge service road to le arebiya BES...,NaN
7439,unplanned,vehicle_breakdown,Bmtc bus off road agide Sir,NaN
2226,unplanned,vehicle_breakdown,ಬ್ರೇಕ್ ಸಮಸ್ಯೆ ಯಿಂದ ವಾಹನ ಕೆಟ್ಟು ನಿಂತಿದೆ ಸರ್,NaN
4096,unplanned,vehicle_breakdown,vehicles tyre blast,NaN
3130,planned,construction,Hospital road white tapping,NaN
3371,unplanned,vehicle_breakdown,NaN,NaN
6965,unplanned,vehicle_breakdown,NaN,NaN
458,unplanned,vehicle_breakdown,NaN,NaN
5116,unplanned,vehicle_breakdown,Hgv vhicel off raod at toll 02 near devenhall...,NaN
1429,unplanned,vehicle_breakdown,ready to 30 minutes,NaN
7333,unplanned,vehicle_breakdown,Starting problem,NaN
4986,unplanned,water_logging,Rain water,NaN
4291,unplanned,vehicle_breakdown,Break down,NaN
2824,unplanned,water_logging,164 pillar ibbluru downramp to agar water logg...,NaN
829,unplanned,others,starting problem,NaN
5948,planned,construction,BWSSB WORK IS GOINGON near [LOCATION] service ...,NaN
5569,unplanned,vehicle_breakdown,[LOCATION] onflyover to wards airport BBmp [PE...,NaN
1265,unplanned,vehicle_breakdown,NaN,NaN
1834,unplanned,vehicle_breakdown,"Bmyc bus has broken down below the metro, but ...",NaN
4657,unplanned,vehicle_breakdown,[LOCATION] road towards Banashankari traffic m...,NaN

In [10]:
text_columns = [
    "event_type",
    "event_cause",
    "description",
    "reason_breakdown"
]


df["combined_text"] = (
    df[text_columns]
    .fillna("")
    .astype(str)
    .agg(" ".join, axis=1)
    .str.lower()
)

In [11]:
df["combined_text"].sample(10)

1506        unplanned vehicle_breakdown starting problem
2596           unplanned water_logging toilet fit opened
3409                        unplanned vehicle_breakdown
6395                        unplanned vehicle_breakdown
7982    unplanned others dasarahalli on flyover incomi...
4252               unplanned vehicle_breakdown no driver
392                         unplanned vehicle_breakdown
1872               unplanned vehicle_breakdown break dow
341     unplanned vehicle_breakdown selam bridge towar...
2485    unplanned vehicle_breakdown school bus  puncture
Name: combined_text, dtype: str

In [12]:
parking_keywords = [

    "parking",
    "parked",
    "park",

    "illegal parking",
    "wrong parking",

    "stopped vehicle",
    "standing vehicle",

    "abandoned",

    "blocking",
    "obstruction",
    "lane block"
]

In [13]:
df["is_parking_event"] = (
    df["combined_text"]
    .apply(
        lambda text:
        int(
            any(
                keyword in text
                for keyword in parking_keywords
            )
        )
    )
)

In [14]:
df["is_parking_event"].value_counts()

is_parking_event
0    8132
1      41
Name: count, dtype: int64

In [15]:
df[
    df["is_parking_event"] == 1
][
[
"event_type",
"event_cause",
"description",
"reason_breakdown"
]
].sample(20)

,event_type,event_cause,description,reason_breakdown
7484,unplanned,vehicle_breakdown,Vehicle parked sided at road .traffic moveme...,Cluth plate break ed
3608,unplanned,vehicle_breakdown,one side parking traffic no problem sir,NaN
1743,unplanned,road_conditions,due to road obstruction slow movement of vehic...,NaN
4390,unplanned,others,Parking issue to function hall,NaN
759,unplanned,congestion,Peenya 2nd stage Aigis Auto lpg gas bunk conje...,NaN
5215,unplanned,vehicle_breakdown,Near kalyani tech park [LOCATION] towards kadu...,NaN
7587,unplanned,others,Near by grt junction 3 hours parking towards c...,NaN
1983,unplanned,vehicle_breakdown,The car's brakes are jammed and it is parked i...,NaN
7576,unplanned,vehicle_breakdown,"Banashankari depo, depo number 20 They are par...",NaN
220,unplanned,construction,Road maintenance vehicle parking sir,NaN
7967,planned,vip_movement,Market floyover uppar ramp unknown parsan wron...,NaN
3558,unplanned,vehicle_breakdown,one side parking traffic slow moment sir,NaN
1358,unplanned,road_conditions,bad road condition at kottigepalya bus stop ob...,NaN
4493,unplanned,vehicle_breakdown,Car puncture left side parking,NaN
1736,unplanned,congestion,Due to road obstruction slow movement of the t...,NaN
853,unplanned,vehicle_breakdown,this ambulance breakdown near HMT Bhavan incom...,NaN
5839,unplanned,vehicle_breakdown,Vehicle breakdown parked at half of the road o...,NaN
17,unplanned,others,[LOCATION] parked at ring road sir traffic lit...,NaN
2142,unplanned,pot_holes,pothole becomes obstruction for traffic movement,NaN
7339,unplanned,others,BMTC BUS no. [VEHICLE] Depo no 23 punc...,NaN

In [16]:
parking_df = df[
    df["is_parking_event"] == 1
]


hotspots = (
    parking_df
    .groupby(
        [
        "junction",
        "zone"
        ]
    )
    .size()
    .reset_index(
        name="parking_events"
    )
    .sort_values(
        "parking_events",
        ascending=False
    )
)


hotspots.head(10)

,junction,zone,parking_events
1,AnandRaoJunction,Central Zone 2,2
0,29thMainRdBTM LayoutJunc,South Zone 2,1
2,Bommanahalli,South Zone 2,1
3,ChaudrayaCircle/UdayaTVCircle(CantonmentJunc),Central Zone 2,1
4,Devasandra(k r puram),East Zone 2,1
5,ESI(k r puram),East Zone 1,1
6,GopalGowdaJUnc,Central Zone 2,1
7,K R Circle,Central Zone 2,1
8,Nagavara-ORR Junction,North Zone 1,1
9,RamaiahCircle-UlsoorPoliceStation,Central Zone 2,1

In [19]:
df["event_cause"].value_counts().head(50)
df["reason_breakdown"].value_counts().head(50)
df[
[
"event_cause",
"description",
"reason_breakdown"
]
].sample(30)
keywords = [
    "park",
    "parking",
    "vehicle",
    "stop",
    "halt",
    "obstruct",
    "block",
    "truck",
    "car",
    "bus"
]


for word in keywords:
    count = (
        df["combined_text"]
        .str.contains(
            word,
            na=False
        )
        .sum()
    )

    print(
        word,
        count
    )
    df["event_cause"].unique()
    df["reason_breakdown"].unique()

park 36
parking 17
vehicle 5103
stop 94
halt 3
obstruct 5
block 12
truck 29
car 151
bus 636

In [22]:
df["reason_breakdown"].value_counts().head(50)

reason_breakdown
Starting problem                         22
starting problem                         11
Breakdown                                 8
breakdown                                 6
break down                                5
Puncher                                   5
Tire burst                                4
mechanical problem                        4
Tyre brust                                4
Diesel empty                              3
Gear problem                              3
brek down                                 3
Tyre puncture                             3
clutch plate problem                      2
off road                                  2
Joint cut                                 2
ವೆಹಿಕಲ್ ಬ್ರೇಕ್ ಡೌನ್ ಆಗಿರುತ್ತದೆ            2
Technical                                 2
bairing problem                           2
diesel empty                              2
tyre blast                                2
Tyre blast                                2
puncture                                  2
ಗೇರ್ ಬಾಕ್ಸ್ ಪ್ರಾಬ್ಲಮ್                     2
No                                        2
Technical problem                         2
Break down                                2
.                                         2
Tyre burest                               1
not gear put                              1
ಬ್ರೇಕ್ ಡೌನ್                               1
Steering problem                          1
Truck problem                             1
Starting Problem                          1
Vehicle starting problem                  1
gear box cut                              1
due to clutch problem sir                 1
Vsbssu                                    1
fuel problem                              1
no                                        1
Storage of fuel                           1
empty diesel                              1
engeen problem                            1
front wheel puncher                       1
front wheel punches                       1
Bolt cut                                  1
Clutch excel problem sir                  1
Starting problem on - Electrical work     1
wheel zam                                 1
vahical breakdown                         1
Name: count, dtype: int64

In [24]:
obstruction_causes = [
    "vehicle_breakdown"
]


df["is_obstruction_event"] = (
    df["event_cause"]
    .isin(obstruction_causes)
    .astype(int)
)
df["is_obstruction_event"].value_counts()

is_obstruction_event
1    4896
0    3277
Name: count, dtype: int64

In [26]:
df["start_datetime"] = pd.to_datetime(
    df["start_datetime"],
    errors="coerce"
)


df["end_datetime"] = pd.to_datetime(
    df["end_datetime"],
    errors="coerce"
)


df["duration_minutes"] = (
    df["end_datetime"]
    -
    df["start_datetime"]
).dt.total_seconds()/60

df[
[
"event_cause",
"duration_minutes"
]
].head()

         event_cause  duration_minutes
0  vehicle_breakdown               NaN
1  vehicle_breakdown               NaN
2             others               NaN
3          tree_fall               NaN
4  vehicle_breakdown               NaN

In [28]:
hotspots = (
    df[df.is_obstruction_event==1]
    .groupby(
        [
            "junction",
            "zone"
        ]
    )
    .agg(
        obstruction_count=("id","count"),

        avg_duration=(
            "duration_minutes",
            "mean"
        ),

        trucks=(
            "veh_type",
            lambda x:
            (x=="truck").sum()
        )
    )
    .reset_index()
)
hotspots.sort_values(
    "obstruction_count",
    ascending=False
).head(10)

,junction,zone,obstruction_count,avg_duration,trucks
250,SatteliteBusStandJunc,West Zone 2,36,NaN,1
179,MekhriCircle,West Zone 2,33,NaN,4
279,TownhallJunction,Central Zone 2,27,NaN,4
300,YeshwanthpuraCircle,West Zone 2,27,NaN,0
82,GokuldasImagesJunc,West Zone 1,25,NaN,1
301,toll gate mysore road,Central Zone 2,23,NaN,1
214,PoliceCornerJunc,Central Zone 2,22,NaN,0
67,Devasandra(k r puram),East Zone 2,21,NaN,1
40,BigBazaarJunction(OldMadrasRd),Central Zone 1,20,NaN,0
299,YelhankaCircle,North Zone 2,20,NaN,1

In [29]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()


cols=[
    "obstruction_count",
    "avg_duration",
    "trucks"
]


hotspots[
[c+"_scaled" for c in cols]
]=scaler.fit_transform(
    hotspots[cols]
)
hotspots["risk_score"] = (

0.5 *
hotspots["obstruction_count_scaled"]

+

0.3 *
hotspots["avg_duration_scaled"]

+

0.2 *
hotspots["trucks_scaled"]

)*100

hotspots.sort_values(
    "risk_score",
    ascending=False
).head(10)


df["hour"] = (
    df.start_datetime.dt.hour
)


peak_times = (
df[df.is_obstruction_event==1]
.groupby(
[
"junction",
"hour"
]
)
.size()
.reset_index(name="events")
)


peak_times.sort_values(
"events",
ascending=False
).head()

                            junction  hour  events
1153             YeshwanthpuraCircle  21.0       8
295               GokuldasImagesJunc  21.0       7
664                     MekhriCircle  23.0       7
135   BigBazaarJunction(OldMadrasRd)   4.0       6
974                    SilkBoardJunc  19.0       6

In [30]:
risk_df = (
    df[df.is_obstruction_event==1]
    .groupby(
        [
            "junction",
            "zone",
            "hour"
        ]
    )
    .agg(

        event_frequency=(
            "id",
            "count"
        ),

        avg_duration=(
            "duration_minutes",
            "mean"
        ),

        truck_count=(
            "veh_type",
            lambda x:
            x.astype(str)
             .str.lower()
             .str.contains("truck")
             .sum()
        ),

        road_closure_count=(
            "requires_road_closure",
            "sum"
        )
    )
    .reset_index()
)

risk_df.head()

,junction,zone,hour,event_frequency,avg_duration,truck_count,road_closure_count
0,17th Mn 1st Crs Aishwarya Stores Jn,South Zone 2,3.0,1,NaN,0,0
1,27th Cross Jayanagar(Ganapathi Temple),South Zone 1,6.0,1,NaN,1,0
2,29thMainRdBTM LayoutJunc,South Zone 2,19.0,1,NaN,1,0
3,29thMainRdBTM LayoutJunc,South Zone 2,20.0,1,NaN,0,0
4,5thMainHSR,South Zone 2,20.0,1,NaN,0,0

In [32]:
risk_df = risk_df.fillna(0)

In [33]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()


features=[
    "event_frequency",
    "avg_duration",
    "truck_count",
    "road_closure_count"
]


scaled = scaler.fit_transform(
    risk_df[features]
)

In [34]:
for i,col in enumerate(features):
    risk_df[col+"_scaled"] = scaled[:,i]

In [35]:
risk_df["risk_score"] = (

    0.45 *
    risk_df.event_frequency_scaled

    +

    0.30 *
    risk_df.avg_duration_scaled

    +

    0.15 *
    risk_df.truck_count_scaled

    +

    0.10 *
    risk_df.road_closure_count_scaled

)*100

In [36]:
risk_df[
[
"junction",
"hour",
"event_frequency",
"risk_score"
]
].sort_values(
"risk_score",
ascending=False
).head(10)

                       junction  hour  event_frequency  risk_score
101   BangaloreBodyBuildersJunc  21.0                6    45.00005
917               SilkBoardJunc  19.0                6    45.00005
270          GokuldasImagesJunc  21.0                7    45.00005
1083        YeshwanthpuraCircle  21.0                6    37.50005
217       Devasandra(k r puram)  18.0                6    37.50005
864       SatteliteBusStandJunc   6.0                5    35.00005
71        BMTCJunction-K H Road   2.0                1    35.00000
618                MekhriCircle   4.0                4    30.00005
615                MekhriCircle   1.0                4    30.00005
1096      toll gate mysore road  22.0                5    30.00005

In [37]:
def recommend(row):

    if row.risk_score >= 80:
        return (
        f"Deploy team at {int(row.hour)-1}:30"
        )

    elif row.risk_score >=50:
        return "Increase monitoring"

    else:
        return "Normal patrol"


risk_df["recommendation"] = (
    risk_df.apply(
        recommend,
        axis=1
    )
)

In [38]:
risk_df[
[
"junction",
"risk_score",
"hour",
"recommendation"
]
].sort_values(
"risk_score",
ascending=False
).head()

                       junction  risk_score  hour recommendation
101   BangaloreBodyBuildersJunc    45.00005  21.0  Normal patrol
917               SilkBoardJunc    45.00005  19.0  Normal patrol
270          GokuldasImagesJunc    45.00005  21.0  Normal patrol
1083        YeshwanthpuraCircle    37.50005  21.0  Normal patrol
217       Devasandra(k r puram)    37.50005  18.0  Normal patrol

In [39]:
risk_df[
[
"event_frequency",
"avg_duration",
"truck_count",
"road_closure_count"
]
].describe()

       event_frequency  avg_duration  truck_count  road_closure_count
count      1099.000000   1099.000000  1099.000000         1099.000000
mean          1.383076     29.054697     0.060965            0.069154
std           0.765683    963.022493     0.250528            0.257394
min           1.000000     -0.053583     0.000000            0.000000
25%           1.000000      0.000000     0.000000            0.000000
50%           1.000000      0.000000     0.000000            0.000000
75%           2.000000      0.000000     0.000000            0.000000
max           7.000000  31925.326050     2.000000            2.000000

In [40]:
def peak_weight(hour):

    # morning peak
    if 8 <= hour <= 11:
        return 1

    # evening peak
    if 17 <= hour <= 21:
        return 1

    return 0


risk_df["peak_hour"] = (
    risk_df["hour"]
    .apply(peak_weight)
)

In [41]:
from sklearn.preprocessing import MinMaxScaler

features=[
    "event_frequency",
    "avg_duration",
    "peak_hour"
]

scaler=MinMaxScaler()


scaled=scaler.fit_transform(
    risk_df[features]
)


for i,col in enumerate(features):
    risk_df[col+"_scaled"]=scaled[:,i]

In [42]:
risk_df["risk_score"] = (

    0.60 *
    risk_df.event_frequency_scaled

    +

    0.25 *
    risk_df.avg_duration_scaled

    +

    0.15 *
    risk_df.peak_hour_scaled

)*100

In [45]:
risk_df[
[
"junction",
"risk_score",
"hour",
"event_frequency",
"recommendation"
]
].sort_values(
"risk_score",
ascending=False
).head(10)

,junction,risk_score,hour,event_frequency,recommendation
270,GokuldasImagesJunc,75.000042,21.0,7,Deploy response team at 20:30
101,BangaloreBodyBuildersJunc,65.000042,21.0,6,Increase monitoring
217,Devasandra(k r puram),65.000042,18.0,6,Increase monitoring
1083,YeshwanthpuraCircle,65.000042,21.0,6,Increase monitoring
917,SilkBoardJunc,65.000042,19.0,6,Increase monitoring
134,BigBazaarJunction(OldMadrasRd),55.000042,19.0,5,Increase monitoring
621,MekhriCircle,55.000042,9.0,5,Increase monitoring
269,GokuldasImagesJunc,45.000042,20.0,4,Increase monitoring
788,RajeshwariJunc,45.000042,20.0,4,Increase monitoring
489,KhodaysCircle(DV UrsCircle),45.000042,21.0,4,Increase monitoring

In [44]:
def recommend(row):

    if row.risk_score >=70:
        return (
        f"Deploy response team at {int(row.hour)-1}:30"
        )

    elif row.risk_score >=40:
        return "Increase monitoring"

    else:
        return "Normal patrol"


risk_df["recommendation"] = (
    risk_df.apply(
        recommend,
        axis=1
    )
)

In [46]:
df["day_of_week"] = (
    df.start_datetime.dt.dayofweek
)


df["month"] = (
    df.start_datetime.dt.month
)

In [47]:
ml_df = (
    df[df.is_obstruction_event==1]
    .groupby(
        [
            "junction",
            "zone",
            "hour",
            "day_of_week"
        ]
    )
    .agg(
        event_frequency=("id","count"),

        avg_duration=(
            "duration_minutes",
            "mean"
        ),

        vehicle_types=(
            "veh_type",
            "nunique"
        )
    )
    .reset_index()
)


ml_df.fillna(0,inplace=True)

,junction,zone,hour,day_of_week,event_frequency,avg_duration,vehicle_types
0,17th Mn 1st Crs Aishwarya Stores Jn,South Zone 2,3.0,3.0,1,0.0,1
1,27th Cross Jayanagar(Ganapathi Temple),South Zone 1,6.0,4.0,1,0.0,1
2,29thMainRdBTM LayoutJunc,South Zone 2,19.0,2.0,1,0.0,1
3,29thMainRdBTM LayoutJunc,South Zone 2,20.0,6.0,1,0.0,1
4,5thMainHSR,South Zone 2,20.0,1.0,1,0.0,1
...,...,...,...,...,...,...,...
1348,toll gate mysore road,Central Zone 2,21.0,5.0,1,0.0,1
1349,toll gate mysore road,Central Zone 2,22.0,3.0,2,0.0,2
1350,toll gate mysore road,Central Zone 2,22.0,6.0,3,0.0,1
1351,toll gate mysore road,Central Zone 2,23.0,2.0,1,0.0,1
1352,toll gate mysore road,West Zone 2,20.0,4.0,1,0.0,1

In [48]:
ml_df.head()

,junction,zone,hour,day_of_week,event_frequency,avg_duration,vehicle_types
0,17th Mn 1st Crs Aishwarya Stores Jn,South Zone 2,3.0,3.0,1,0.0,1
1,27th Cross Jayanagar(Ganapathi Temple),South Zone 1,6.0,4.0,1,0.0,1
2,29thMainRdBTM LayoutJunc,South Zone 2,19.0,2.0,1,0.0,1
3,29thMainRdBTM LayoutJunc,South Zone 2,20.0,6.0,1,0.0,1
4,5thMainHSR,South Zone 2,20.0,1.0,1,0.0,1

In [49]:
from sklearn.preprocessing import MinMaxScaler


scaler=MinMaxScaler()


cols=[
"event_frequency",
"avg_duration"
]


ml_df[
[c+"_scaled" for c in cols]
]=scaler.fit_transform(
    ml_df[cols]
)

In [50]:
ml_df["risk_score"]=(

0.7*
ml_df.event_frequency_scaled

+

0.3*
ml_df.avg_duration_scaled

)*100

In [51]:
ml_df[
[
"junction",
"hour",
"risk_score"
]
].head()

                                 junction  hour  risk_score
0     17th Mn 1st Crs Aishwarya Stores Jn   3.0     0.00005
1  27th Cross Jayanagar(Ganapathi Temple)   6.0     0.00005
2                29thMainRdBTM LayoutJunc  19.0     0.00005
3                29thMainRdBTM LayoutJunc  20.0     0.00005
4                              5thMainHSR  20.0     0.00005

In [52]:
!pip install xgboost

Requirement already satisfied: xgboost in /Users/ravidindisaiprasannakumar/hackathon/.venv/lib/python3.14/site-packages (3.3.0)
Requirement already satisfied: numpy in /Users/ravidindisaiprasannakumar/hackathon/.venv/lib/python3.14/site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in /Users/ravidindisaiprasannakumar/hackathon/.venv/lib/python3.14/site-packages (from xgboost) (1.17.1)

In [53]:
from xgboost import XGBRegressor

from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_absolute_error
X = ml_df.drop(
    "risk_score",
    axis=1
)

y = ml_df["risk_score"]

In [54]:
X=pd.get_dummies(X)

In [55]:
X_train,X_test,y_train,y_test = (
    train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )
)

In [56]:
model=XGBRegressor(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05
)


model.fit(
    X_train,
    y_train
)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [57]:
pred=model.predict(
    X_test
)


mae=mean_absolute_error(
    y_test,
    pred
)


mae

0.11070067099117617

In [58]:
import joblib


joblib.dump(
    model,
    "../models/risk_model.pkl"
)


joblib.dump(
    X.columns,
    "../models/model_columns.pkl"
)

['../models/model_columns.pkl']